
CREATE TABLE public."Connects" (
  id bigint generated by default as identity not null,
  name text not null,
  link text not null,
  constraint "Connects_pkey" primary key (id)
);

ALTER TABLE public."Connects" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."Connects" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "No public writes" ON public."Connects" FOR INSERT TO anon, authenticated WITH CHECK (false);
CREATE POLICY "No public writes update" ON public."Connects" FOR UPDATE TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY "No public writes delete" ON public."Connects" FOR DELETE TO anon, authenticated USING (false);
