
CREATE TABLE public."Site config" (
  id bigint generated by default as identity not null,
  title text null,
  name text null,
  slong text null,
  description text null,
  logo text null,
  constraint "Site config_pkey" primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public."Site config" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."Site config"
  FOR SELECT TO anon, authenticated USING (true);
