CREATE TABLE public."Groups" (
  id bigint generated by default as identity not null,
  name text null,
  link text null,
  constraint "Groups_pkey" primary key (id)
);

ALTER TABLE public."Groups" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
ON public."Groups"
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "No public writes insert"
ON public."Groups"
FOR INSERT
TO anon, authenticated
WITH CHECK (false);

CREATE POLICY "No public writes update"
ON public."Groups"
FOR UPDATE
TO anon, authenticated
USING (false)
WITH CHECK (false);

CREATE POLICY "No public writes delete"
ON public."Groups"
FOR DELETE
TO anon, authenticated
USING (false);