CREATE TABLE public."Refund and exchange policy" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  markdown text null,
  constraint "Refund and exchange policy_pkey" primary key (id)
);

ALTER TABLE public."Refund and exchange policy" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."Refund and exchange policy" FOR SELECT TO anon, authenticated USING (true);