CREATE TABLE public."Products" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  category text not null,
  description text null,
  price numeric null,
  image text null,
  stock boolean null default true,
  duration bigint null,
  constraint products_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE public."Products" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."Products"
  FOR SELECT TO anon, authenticated USING (true);