CREATE TABLE public."Channels" (
  id bigint generated by default as identity not null,
  name text null,
  link text null,
  constraint Channels_pkey primary key (id)
);

ALTER TABLE public."Channels" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."Channels" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "No public writes" ON public."Channels" FOR INSERT TO anon, authenticated WITH CHECK (false);
CREATE POLICY "No public writes delete" ON public."Channels" FOR DELETE TO anon, authenticated USING (false);
CREATE POLICY "No public writes update" ON public."Channels" FOR UPDATE TO anon, authenticated USING (false) WITH CHECK (false);