
CREATE TABLE public."Terms of Service" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  constraint "Terms of Service_pkey" primary key (id)
) TABLESPACE pg_default;
