
CREATE TABLE IF NOT EXISTS public."Reviews" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  "FullName" text,
  star bigint check (star >= 1 AND star <= 5),
  profile text,
  description text
);
ALTER TABLE public."Reviews" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read reviews" ON public."Reviews" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public can insert reviews" ON public."Reviews" FOR INSERT TO anon, authenticated WITH CHECK (star >= 1 AND star <= 5 AND char_length(coalesce("FullName",'')) <= 100 AND char_length(coalesce(description,'')) <= 1000);
