CREATE TABLE public."Category" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  constraint Category_pkey primary key (id)
);

ALTER TABLE public."Category" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."Category"
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "No public writes" ON public."Category"
  FOR INSERT TO anon, authenticated
  WITH CHECK (false);

CREATE POLICY "No public writes update" ON public."Category"
  FOR UPDATE TO anon, authenticated
  USING (false) WITH CHECK (false);

CREATE POLICY "No public writes delete" ON public."Category"
  FOR DELETE TO anon, authenticated
  USING (false);