CREATE TABLE public."All-About" (
  id bigint generated by default as identity not null,
  "AboutName" text null,
  "AboutMD" text null,
  created_at timestamp with time zone not null default now(),
  constraint "All-About_pkey" primary key (id)
);

ALTER TABLE public."All-About" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
ON public."All-About"
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "No public writes insert"
ON public."All-About"
FOR INSERT
TO anon, authenticated
WITH CHECK (false);

CREATE POLICY "No public writes update"
ON public."All-About"
FOR UPDATE
TO anon, authenticated
USING (false)
WITH CHECK (false);

CREATE POLICY "No public writes delete"
ON public."All-About"
FOR DELETE
TO anon, authenticated
USING (false);