CREATE TABLE public."All-Policy" (
  id bigint generated by default as identity not null,
  "PolicyName" text null,
  "PolicyMD" text null,
  created_at timestamp with time zone not null default now(),
  constraint "All-Policy_pkey" primary key (id)
);

ALTER TABLE public."All-Policy" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
ON public."All-Policy"
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "No public writes insert"
ON public."All-Policy"
FOR INSERT
TO anon, authenticated
WITH CHECK (false);

CREATE POLICY "No public writes update"
ON public."All-Policy"
FOR UPDATE
TO anon, authenticated
USING (false)
WITH CHECK (false);

CREATE POLICY "No public writes delete"
ON public."All-Policy"
FOR DELETE
TO anon, authenticated
USING (false);