CREATE TABLE IF NOT EXISTS public."Sliders" (
  id bigint generated by default as identity not null primary key,
  images text null,
  created_at timestamp with time zone not null default now()
);

ALTER TABLE public."Sliders" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
  ON public."Sliders" FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "No public writes"
  ON public."Sliders" FOR INSERT
  TO anon, authenticated
  WITH CHECK (false);

CREATE POLICY "No public writes update"
  ON public."Sliders" FOR UPDATE
  TO anon, authenticated
  USING (false) WITH CHECK (false);

CREATE POLICY "No public writes delete"
  ON public."Sliders" FOR DELETE
  TO anon, authenticated
  USING (false);