CREATE TABLE public."FAQ" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  question text null,
  answer text null,
  constraint FAQ_pkey primary key (id)
);

ALTER TABLE public."FAQ" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."FAQ" FOR SELECT TO anon, authenticated USING (true);